# This is a basic workflow to help you get started with Actions

name: Publish Template

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      commit_message:
        description: "Commit Message"
        required: true
      other:
        description: "Other Arguments"
        required: False

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: checkUser
        with:
          require: 'admin'
      - name: Wrong Privilege
        if: steps.checkUser.outputs.require-result == 'false'
        run: exit 1

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
         pip install GitPython

      - name: Publish
        env:
            GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          cd .github/scripts/
          python share_common.py --commit_message "${{ github.event.inputs.commit_message}}" ${{ github.event.inputs.other}}
